# =============================
#   Site Information
# =============================

title: "Derek Nugroho"
name: "Derek Nugroho"
description: "Data Scientist | Machine Learning | Turning Data Into Insight"
email: "derek.nugroho@example.com"
github_username: "dereknugroho"
linkedin: "https://www.linkedin.com/in/dereknugroho/"
resume: "/assets/Derek_Nugroho_Resume.pdf"

# =============================
#   Theme Settings
# =============================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"   # Other options: air, mint, contrast, dark, sunrise
search: true                       # Enables search bar
markdown: kramdown

# =============================
#   Author Profile
# =============================

author:
  name: "Derek Nugroho"
  avatar: "/assets/images/42-photo.jpg"   # Add your photo in assets/images
  bio: "Data scientist with a background in finance, exploring data-driven decision making and automation."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dereknugroho/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dereknugroho"
    - label: "Résumé (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/Derek_Nugroho_Resume.pdf"

# =============================
#   Footer Links
# =============================

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dereknugroho/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dereknugroho"

# =============================
#   Build Settings
# =============================

permalink: /:title/
timezone: "America/Halifax"   # Adjust to your timezone
include:
  - _pages

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
