# To do
# - Remove "Recent Posts" from homepage
# - Add content to homepage
# - Sections to homepage
# - Smooth scroll
# - Light/dark theme toggle


# =============================
#   Site Information
# =============================

title: "Derek Nugroho"
name: "Derek Nugroho"
description: "Data Scientist"
email: "derek.nugroho@gmail.com"
github_username: "dereknugroho"
linkedin: "https://www.linkedin.com/in/dereknugroho/"
resume: "/assets/Derek_Nugroho_Resume.pdf"

# =============================
#   Theme Settings
# =============================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"   # Other options: air, mint, contrast, dark, sunrise
markdown: kramdown

# =============================
#   Author Profile
# =============================

author:
  name: "Derek Nugroho"
  avatar: "/assets/images/initials.png"   # Add your photo in assets/images
  bio: "Sushi enthusiast with a master's in data science."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dereknugroho/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dereknugroho"
    - label: "Résumé (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/Derek_Nugroho_Resume.pdf"

# =============================
#   Footer Links
# =============================

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dereknugroho/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dereknugroho"

# =============================
#   Build Settings
# =============================

permalink: /:title/
timezone: "America/Halifax"   # Adjust to your timezone
include:
  - _pages

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# # Disable blog index as homepage
# show_excerpts: false
# paginate: 0

# Smooth scrolling
minimal_mistakes_skin: "dark"
scroll_top: true

# Add at the bottom
sass:
  style: compressed