# To do
# Remove RSS feed from footer
# Put navbar items in hamburger menu on mobile
# Sticky navbar
# Back to top

# =============================
#   Site Information
# =============================

title: "Derek Nugroho"
name: "Derek Nugroho"
description: "Data Scientist"
email: "derek.nugroho@gmail.com"
github_username: "dereknugroho"
linkedin: "https://www.linkedin.com/in/dereknugroho/"
resume: "/assets/Derek_Nugroho_Resume.pdf"

# =============================
#   Theme Settings
# =============================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"   # Other options: air, mint, contrast, dark, sunrise
markdown: kramdown
scroll_top: true

# =============================
#   Author Profile
# =============================

author:
  name: "Derek Nugroho"
  avatar: "/assets/images/initials.png"
  bio: "Sushi enthusiast with a master's in data science."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dereknugroho/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dereknugroho"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@dereknugroho"
    # - label: "Résumé (PDF)"
    #   icon: "fas fa-fw fa-file-pdf"
    #   url: "/assets/Derek_Nugroho_Resume.pdf"

# =============================
#   Top Navigation
# =============================

navigation:
  - title: "Education"
    url: "/#education"
  - title: "Projects"
    url: "/#projects"
  - title: "Contact"
    url: "/#contact"

header_pages: []

# =============================
#   Footer Links
# =============================

footer:
  show_rss: false   # Disable the default RSS link
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/dereknugroho/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dereknugroho"

# =============================
#   Feed Settings
# =============================

feed:
  path: ""   # Completely disable RSS feed generation

# =============================
#   Build Settings
# =============================

permalink: /:title/
timezone: "America/Halifax"
include:
  - _pages

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Smooth scrolling
minimal_mistakes_skin: "dark"

# Add at the bottom
sass:
  style: compressed
